# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $jwtKey: '%env(JWT_KEY)%'
            $jwtIssuedBy: '%env(JWT_ISSUED_BY)%'
            $jwtPermittedFor: '%env(JWT_PERMITTED_FOR)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Handlers need to be public for locator
    App\Domain\Handler\:
        resource: '../src/Domain/Handler'
        public: true

    # Command Bus
    League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor:
    League\Tactician\Handler\MethodNameInflector\HandleInflector:
    League\Tactician\Handler\CommandHandlerMiddleware:
        arguments:
            - '@League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor'
            - '@App\Domain\Core\Locator'
            - '@League\Tactician\Handler\MethodNameInflector\HandleInflector'

    League\Tactician\Plugins\LockingMiddleware:
    League\Tactician\Doctrine\ORM\TransactionMiddleware:
        arguments:
            - '@doctrine.orm.entity_manager'

    League\Tactician\CommandBus:
        arguments:
            -
                - '@League\Tactician\Plugins\LockingMiddleware'
                - '@League\Tactician\Doctrine\ORM\TransactionMiddleware'
                - '@League\Tactician\Handler\CommandHandlerMiddleware'