App\Domain\Command\UpdatePostCommand:
  properties:
    title:
      - NotBlank:
          message: Le champs titre est obligatoire
      - Length:
          max: 255
          maxMessage: Le champs titre est limité à {{ limit }} caractères
    abstract:
      - NotBlank:
          message: Le champs extrait est obligatoire
      - Length:
          max: 255
          maxMessage: Le champs extrait est limité à {{ limit }} caractères
    content:
      - NotBlank:
          message: Le champs contenu est obligatoire
  constraints:
    - App\Domain\Validator\Constraints\TitleAvailable: ~